image: php
labels:
  - role=php
cpuset: "4-7"
working_dir: /src
cap_drop:
  - ALL
cap_add:
  - CHOWN
volumes:
  - env-storage:/src/env:rw
  - huggingface-storage:/root/.cache:rw
environment:
  - PROJECT=$COMPOSE_PROJECT_NAME
  - PROJECT_ENV=$ENV
  - PROJECT_REV=$REVISION
  - GITHUB_TOKENS=$GITHUB_TOKENS
  - GMAIL_ACCOUNT=$GMAIL_ACCOUNT
  - GMAIL_PASSWORD=$GMAIL_PASSWORD
