image: nginx
labels:
  - role=nginx
cpuset: "4-5"
working_dir: /src
ports:
  - '80:80'
  - '443:443'
cap_drop:
  - ALL
cap_add:
  - NET_BIND_SERVICE
  - SYS_NICE
  - CHOWN
  - DAC_OVERRIDE
  - SETGID
  - SETUID
volumes:
  - env-storage:/src/env
  - $SSL_CERT_PEM:/etc/nginx/ssl/cert.pem
  - $SSL_CERT_KEY:/etc/nginx/ssl/cert.key
environment:
  - PROJECT=$COMPOSE_PROJECT_NAME
