image: manticoresearch/manticore:dev-6.2.13-83733d1
labels:
  - role=manticore
restart: "always"
environment:
  - EXTRA=1
volumes:
  - manticore-storage:/var/lib/manticore:rw
  - $DOCKER_ROOT/containers/manticore/backup:/docker-entrypoint-initdb.d:rw
