image: queue
labels:
  - role=queue
cpuset: "6-7"
restart: unless-stopped
entrypoint: ["beanstalkd"]
ports:
  - '4444:4444'
command:
  - "-l"
  - "0.0.0.0"
  - "-p"
  - "4444"
  - "-z"
  - "262144"
  - "-VV"
stop_signal: SIGINT
